apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofileapp
  labels:
    app: vprofile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vprofile
  template:
    metadata:
      labels:
        app: vprofile
    spec:
      containers:
      - name: vprofileapp
        image: gopi1998/vprofileapp:${BUILD_NUMBER}
        ports:
        - containerPort: 80