apiVersion: v1
kind: Service
metadata:
  name: vprofileservice
spec:
  type: NodePort
  selector:
    app: vprofile
  ports:
    - protocol: TCP
      port: 9898
      targetPort: 80
      nodePort: 30007